# Generated by Django 5.2 on 2025-12-15 09:40

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('audio_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='النص الكتابي للتسجيل')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='المدة بالثواني', null=True, verbose_name='مدة التسجيل')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', max_length=20, verbose_name='مستوى الصعوبة')),
            ],
            options={
                'verbose_name': 'تسجيل صوتي',
                'verbose_name_plural': 'التسجيلات الصوتية',
            },
        ),
        migrations.CreateModel(
            name='MCQQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المجموعة')),
            ],
            options={
                'verbose_name': 'مجموعة أسئلة MCQ',
                'verbose_name_plural': 'مجموعات أسئلة MCQ',
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('passage_text', models.TextField(verbose_name='نص القطعة')),
                ('passage_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='مصدر القطعة')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', max_length=20, verbose_name='مستوى الصعوبة')),
            ],
            options={
                'verbose_name': 'قطعة قراءة',
                'verbose_name_plural': 'قطع القراءة',
            },
        ),
        migrations.CreateModel(
            name='SpeakingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفيديو')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='المدة بالثواني', null=True, verbose_name='مدة الفيديو')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'فيديو تحدث',
                'verbose_name_plural': 'فيديوهات التحدث',
            },
        ),
        migrations.CreateModel(
            name='WritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('min_words', models.PositiveIntegerField(default=100, verbose_name='الحد الأدنى للكلمات')),
                ('max_words', models.PositiveIntegerField(default=500, verbose_name='الحد الأقصى للكلمات')),
                ('sample_answer', models.TextField(blank=True, null=True, verbose_name='نموذج إجابة')),
                ('rubric', models.TextField(blank=True, help_text='معايير تقييم الإجابة', null=True, verbose_name='معايير التقييم')),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', max_length=20, verbose_name='مستوى الصعوبة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سؤال كتابة',
                'verbose_name_plural': 'أسئلة الكتابة',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sabr_questions.listeningaudio', verbose_name='التسجيل الصوتي')),
            ],
            options={
                'verbose_name': 'سؤال استماع',
                'verbose_name_plural': 'أسئلة الاستماع',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sabr_questions.mcqquestionset', verbose_name='مجموعة الأسئلة')),
            ],
            options={
                'verbose_name': 'سؤال MCQ',
                'verbose_name_plural': 'أسئلة MCQ',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sabr_questions.readingpassage', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'سؤال قراءة',
                'verbose_name_plural': 'أسئلة القراءة',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sabr_questions.speakingvideo', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'سؤال تحدث',
                'verbose_name_plural': 'أسئلة التحدث',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
