# Generated by Django 5.2 on 2026-04-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('sabr_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='general_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='general.generalskill', verbose_name='General Skill'),
        ),
    ]
