# Generated by Django 5.2 on 2025-12-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningaudio',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='writingquestion',
            name='difficulty_level',
        ),
    ]
