# Generated by Django 5.2 on 2026-02-07 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingquestion',
            name='pass_threshold',
            field=models.PositiveIntegerField(default=60, help_text='النسبة المئوية المطلوبة لاعتبار الإجابة صحيحة (default: 60%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النجاح المطلوبة (%)'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط'),
        ),
    ]
