# Generated by Django 5.2 on 2026-04-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
        ('sabr_questions', '0002_grammarquestion_general_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='esp_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='esp.espskill', verbose_name='Esp Skill'),
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='grammarquestionset',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('STEP', 'Learning Step'), ('IELTS', 'IELTS Exam'), ('LEVEL', 'Level Test'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='listeningaudio',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='speakingvideo',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='vocabularyquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='vocabularyquestionset',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('STEP', 'Learning Step'), ('IELTS', 'IELTS Exam'), ('LEVEL', 'Level Test'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use'), ('ESP', 'Esp')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
    ]
