# Generated by Django 5.2 on 2025-12-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0002_remove_listeningaudio_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الامتحان')),
                ('duration_minutes', models.PositiveIntegerField(help_text='المدة الزمنية المحددة لإنهاء الامتحان', verbose_name='مدة الامتحان (بالدقائق)')),
                ('a1_min_score', models.PositiveIntegerField(default=0, help_text='من 0 إلى هذه الدرجة = A1', verbose_name='الحد الأدنى لمستوى A1')),
                ('a2_min_score', models.PositiveIntegerField(help_text='من الدرجة السابقة إلى هذه الدرجة = A2', verbose_name='الحد الأدنى لمستوى A2')),
                ('b1_min_score', models.PositiveIntegerField(help_text='من الدرجة السابقة إلى هذه الدرجة = B1', verbose_name='الحد الأدنى لمستوى B1')),
                ('b2_min_score', models.PositiveIntegerField(help_text='من الدرجة السابقة فما فوق = B2', verbose_name='الحد الأدنى لمستوى B2')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'امتحان تحديد المستوى',
                'verbose_name_plural': 'امتحانات تحديد المستوى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='listeningaudio',
            options={'ordering': ['placement_test', 'order', 'created_at'], 'verbose_name': 'تسجيل صوتي', 'verbose_name_plural': 'التسجيلات الصوتية'},
        ),
        migrations.AlterModelOptions(
            name='mcqquestionset',
            options={'ordering': ['placement_test', 'order', 'created_at'], 'verbose_name': 'مجموعة أسئلة MCQ', 'verbose_name_plural': 'مجموعات أسئلة MCQ'},
        ),
        migrations.AlterModelOptions(
            name='readingpassage',
            options={'ordering': ['placement_test', 'order', 'created_at'], 'verbose_name': 'قطعة قراءة', 'verbose_name_plural': 'قطع القراءة'},
        ),
        migrations.AlterModelOptions(
            name='speakingvideo',
            options={'ordering': ['placement_test', 'order', 'created_at'], 'verbose_name': 'فيديو تحدث', 'verbose_name_plural': 'فيديوهات التحدث'},
        ),
        migrations.AlterModelOptions(
            name='writingquestion',
            options={'ordering': ['placement_test', 'order', 'created_at'], 'verbose_name': 'سؤال كتابة', 'verbose_name_plural': 'أسئلة الكتابة'},
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='placement_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_audios', to='sabr_questions.placementtest', verbose_name='امتحان تحديد المستوى'),
        ),
        migrations.AddField(
            model_name='mcqquestionset',
            name='placement_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_sets', to='sabr_questions.placementtest', verbose_name='امتحان تحديد المستوى'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='placement_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='sabr_questions.placementtest', verbose_name='امتحان تحديد المستوى'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='placement_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_videos', to='sabr_questions.placementtest', verbose_name='امتحان تحديد المستوى'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='placement_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_questions', to='sabr_questions.placementtest', verbose_name='امتحان تحديد المستوى'),
        ),
    ]
