# Generated by Django 5.2 on 2026-02-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('sabr_questions', '0002_writingquestion_pass_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='للأسئلة المحلولة في الدروس (usage_type=LESSON)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='level_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان المستوى (usage_type=LEVEL_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='unit_exam',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان الوحدة (usage_type=UNIT_EXAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='listeningaudio',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='speakingvideo',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='vocabularyquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
    ]
