# Generated by Django 5.2 on 2026-02-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_levelsunitsquestionbank_delete_questionbank'),
        ('placement_test', '0005_rename_questionbank_placementquestionbank_and_more'),
        ('sabr_questions', '0003_grammarquestion_lesson_grammarquestion_level_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarquestion',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='listeningaudio',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='speakingvideo',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='vocabularyquestion',
            name='question_bank',
        ),
        migrations.RemoveField(
            model_name='writingquestion',
            name='question_bank',
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_grammar_questions', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_grammar_questions', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_listening_audios', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_listening_audios', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_reading_passages', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_reading_passages', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_speaking_videos', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_speaking_videos', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_vocabulary_questions', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_vocabulary_questions', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='levels_units_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_writing_questions', to='levels.levelsunitsquestionbank', verbose_name='بنك أسئلة Levels/Units'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='placement_question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_writing_questions', to='placement_test.placementquestionbank', verbose_name='بنك أسئلة Placement'),
        ),
    ]
