# Generated by Django 5.2 on 2026-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0003_grammarquestion_esp_skill_listeningaudio_esp_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='english_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='شرح الإجابة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='english_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='شرح الإجابة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='english_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='شرح الإجابة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='english_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='شرح الإجابة بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='english_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='شرح الإجابة بالإنجليزية'),
        ),
    ]
