# Generated by Django 5.2 on 2026-02-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
        ('sabr_questions', '0004_remove_grammarquestion_question_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='ielts_lesson_pack',
            field=models.ForeignKey(blank=True, help_text='لأسئلة امتحان IELTS (usage_type=IELTS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.lessonpack', verbose_name='IELTS Lesson Pack'),
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='listeningaudio',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='speakingvideo',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='vocabularyquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
    ]
