# Generated by Django 5.2 on 2026-02-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0005_grammarquestion_ielts_lesson_pack_and_more'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='step_skill',
            field=models.ForeignKey(blank=True, help_text='لأسئلة STEP (usage_type=STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='step.stepskill', verbose_name='STEP Skill'),
        ),
    ]
