# Generated by Django 5.2 on 2026-03-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
        ('sabr_questions', '0006_grammarquestion_step_skill_listeningaudio_step_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='ielts_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_questions', to='ielts.ieltslesson', verbose_name='IELTS Lesson'),
        ),
    ]
