# Generated by Django 5.2 on 2026-03-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0007_grammarquestion_ielts_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='listeningaudio',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='speakingvideo',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='vocabularyquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='usage_type',
            field=models.CharField(choices=[('QUESTION_BANK', 'Question Bank'), ('PLACEMENT', 'Placement Test'), ('LESSON', 'Lesson Content'), ('UNIT_EXAM', 'Unit Exam'), ('LEVEL_EXAM', 'Level Exam'), ('IELTS', 'IELTS Exam'), ('IELTS_LESSON', 'IELTS Lesson'), ('GENERAL', 'General Use')], db_index=True, default='QUESTION_BANK', max_length=20, verbose_name='نوع الاستخدام'),
        ),
    ]
