# Generated by Django 5.2 on 2026-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabr_questions', '0008_alter_grammarquestion_usage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='speakingvideo',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='vocabularyquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'سهل'), ('MEDIUM', 'متوسط'), ('HARD', 'صعب')], db_index=True, default='MEDIUM', max_length=10, verbose_name='مستوى الصعوبة'),
        ),
    ]
