# Generated by Django 5.2 on 2026-04-14 09:54

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكاتيجوري')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'Esp Category',
                'verbose_name_plural': 'Esp Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EspExtractedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الكتاب')),
                ('pdf_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف PDF')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp_extracted_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esp Extracted Book',
                'verbose_name_plural': 'Esp Extracted Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EspExtractedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الميديا')),
                ('media_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف الميديا')),
                ('media_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=10)),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='الترانسكريبت')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp_extracted_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esp Extracted Media',
                'verbose_name_plural': 'Esp Extracted Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EspSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('skill_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع المهارة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='esp.espcategory', verbose_name='الكاتيجوري')),
            ],
            options={
                'verbose_name': 'Esp Skill',
                'verbose_name_plural': 'Esp Skills',
                'ordering': ['order', 'skill_type'],
            },
        ),
        migrations.CreateModel(
            name='EspAIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=20, verbose_name='نوع المهارة')),
                ('skill_title', models.CharField(max_length=200, verbose_name='عنوان المهارة')),
                ('skill_description', models.TextField(blank=True, null=True, verbose_name='وصف المهارة')),
                ('no_easy', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة السهلة')),
                ('no_medium', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المتوسطة')),
                ('no_hard', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة الصعبة')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('questions_created', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المُنشأة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_jobs', to='esp.espcategory', verbose_name='الكاتيجوري')),
                ('books', models.ManyToManyField(blank=True, related_name='generation_jobs', to='esp.espextractedbook')),
                ('media', models.ManyToManyField(blank=True, related_name='generation_jobs', to='esp.espextractedmedia')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='esp.espskill', verbose_name='المهارة المُنشأة')),
            ],
            options={
                'verbose_name': 'Esp AI Generation Job',
                'verbose_name_plural': 'Esp AI Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEspProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('viewed_questions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المكتملة')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='esp.espskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student Esp Progress',
                'verbose_name_plural': 'Student Esp Progress',
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentEspQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('is_solved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('used_show_answer', models.BooleanField(default=False, verbose_name='استخدم show answer')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='esp.espskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student Esp Question Attempt',
                'verbose_name_plural': 'Student Esp Question Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='esp_student_student_9dbfb5_idx'), models.Index(fields=['question_type', 'question_id'], name='esp_student_questio_0564d8_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
    ]
