# Generated by Django 5.2 on 2026-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='session_price',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='البريد الالكتروني'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='رقم واتساب الطالب')),
                ('recurrence', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('once', 'مرة واحدة')], max_length=10, verbose_name='نظام التكرار')),
                ('duration', models.CharField(help_text='مثال: شهرين، 3 أشهر', max_length=100, verbose_name='المدة المطلوبة')),
                ('curriculum', models.TextField(verbose_name='المادة أو المنهج المطلوب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_programs', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_programs', to='booking.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'تخصيص برنامج',
                'verbose_name_plural': 'طلبات تخصيص البرامج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('time', models.TimeField(verbose_name='الساعة')),
                ('custom_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.customprogram', verbose_name='طلب التخصيص')),
            ],
            options={
                'verbose_name': 'موعد التخصيص',
                'verbose_name_plural': 'مواعيد التخصيص',
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان البرنامج')),
                ('description', models.TextField(verbose_name='وصف البرنامج')),
                ('recurrence', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('once', 'مرة واحدة')], max_length=10, verbose_name='نظام التكرار')),
                ('duration', models.CharField(help_text='مثال: شهرين، 3 أشهر', max_length=100, verbose_name='مدة البرنامج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة البرنامج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='booking.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'برنامج تعليمي',
                'verbose_name_plural': 'البرامج التعليمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('time', models.TimeField(verbose_name='الساعة')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'موعد البرنامج',
                'verbose_name_plural': 'مواعيد البرنامج',
                'ordering': ['day_of_week', 'time'],
                'constraints': [models.UniqueConstraint(fields=('program', 'day_of_week', 'time'), name='unique_program_schedule')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='معرف الدفع من Moyasar')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('pending', 'في الانتظار')], default='pending', max_length=10, verbose_name='حالة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='booking.program', verbose_name='البرنامج')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'program'), name='unique_subscription')],
            },
        ),
    ]
