# Generated by Django 5.2 on 2026-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_teacher_session_price_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='الرقم المرجعي'),
        ),
    ]
