# Generated by Django 5.2 on 2026-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_subscription_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='كود المدرس'),
        ),
    ]
