# Generated by Django 5.2 on 2026-04-11 09:42

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكاتيجوري')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'General Category',
                'verbose_name_plural': 'General Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('skill_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع المهارة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='general.generalcategory', verbose_name='الكاتيجوري')),
            ],
            options={
                'verbose_name': 'General Skill',
                'verbose_name_plural': 'General Skills',
                'ordering': ['order', 'skill_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentGeneralProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('viewed_questions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المكتملة')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='general.generalskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student General Progress',
                'verbose_name_plural': 'Student General Progress',
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentGeneralQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('is_solved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('used_show_answer', models.BooleanField(default=False, verbose_name='استخدم show answer')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='general.generalskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student General Question Attempt',
                'verbose_name_plural': 'Student General Question Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='general_stu_student_304d03_idx'), models.Index(fields=['question_type', 'question_id'], name='general_stu_questio_7c954e_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
    ]
