# Generated by Django 5.2 on 2026-04-11 09:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExtractedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الكتاب')),
                ('pdf_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف PDF')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_extracted_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Extracted Book',
                'verbose_name_plural': 'General Extracted Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralExtractedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الميديا')),
                ('media_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف الميديا')),
                ('media_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=10)),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='الترانسكريبت')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_extracted_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Extracted Media',
                'verbose_name_plural': 'General Extracted Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralAIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=20, verbose_name='نوع المهارة')),
                ('skill_title', models.CharField(max_length=200, verbose_name='عنوان المهارة')),
                ('skill_description', models.TextField(blank=True, null=True, verbose_name='وصف المهارة')),
                ('no_easy', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة السهلة')),
                ('no_medium', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المتوسطة')),
                ('no_hard', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة الصعبة')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('questions_created', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المُنشأة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_jobs', to='general.generalcategory', verbose_name='الكاتيجوري')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='general.generalskill', verbose_name='المهارة المُنشأة')),
                ('books', models.ManyToManyField(blank=True, related_name='generation_jobs', to='general.generalextractedbook')),
                ('media', models.ManyToManyField(blank=True, related_name='generation_jobs', to='general.generalextractedmedia')),
            ],
            options={
                'verbose_name': 'General AI Generation Job',
                'verbose_name_plural': 'General AI Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
