# Generated by Django 5.2 on 2026-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_generalextractedbook_generalextractedmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalskill',
            name='question_order_type',
            field=models.CharField(choices=[('SEQUENTIAL', 'Sequential (Easy → Medium → Hard)'), ('CYCLIC', 'Cyclic (3 Easy, 3 Medium, 3 Hard, repeat)'), ('RANDOM', 'Random')], default='SEQUENTIAL', max_length=20, verbose_name='طريقة ترتيب الأسئلة'),
        ),
    ]
