# Generated by Django 5.2 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_studentfavoritecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalskill',
            name='skill_type',
            field=models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('GENERAL_PATH', 'General path')], max_length=20, verbose_name='نوع المهارة'),
        ),
    ]
