# Generated by Django 5.2 on 2026-07-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True)),
                ('latest_version', models.CharField(max_length=20)),
                ('minimum_version', models.CharField(max_length=20)),
                ('update_message', models.CharField(blank=True, default='يوجد إصدار جديد من التطبيق، برجاء التحديث.', max_length=255)),
                ('force_update_message', models.CharField(blank=True, default='يجب تحديث التطبيق للاستمرار في استخدامه.', max_length=255)),
                ('store_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
