# Generated by Django 5.2 on 2026-02-18 14:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STEPSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('skill_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('WRITING', 'Writing')], max_length=20, unique=True, verbose_name='نوع المهارة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'STEP Skill',
                'verbose_name_plural': 'STEP Skills',
                'ordering': ['order', 'skill_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentSTEPProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('viewed_questions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المفتوحة')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='step.stepskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student STEP Progress',
                'verbose_name_plural': 'Student STEP Progress',
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentSTEPQuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('WRITING', 'Writing')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفتح')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='step.stepskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_question_views', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student STEP Question View',
                'verbose_name_plural': 'Student STEP Question Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='step_studen_student_1f2acd_idx'), models.Index(fields=['question_type', 'question_id'], name='step_studen_questio_65f787_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
    ]
