# Generated by Django 5.2 on 2026-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepskill',
            name='skill_type',
            field=models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing')], max_length=20, unique=True, verbose_name='نوع المهارة'),
        ),
        migrations.AlterField(
            model_name='studentstepquestionview',
            name='question_type',
            field=models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing')], max_length=20, verbose_name='نوع السؤال'),
        ),
    ]
