# Generated by Django 5.2 on 2026-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_stepskill_skill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepskill',
            name='skill_type',
            field=models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing')], max_length=20, verbose_name='نوع المهارة'),
        ),
    ]
