# Generated by Django 5.2 on 2026-04-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_stepskill_skill_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstepprogress',
            name='viewed_questions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المكتملة'),
        ),
        migrations.CreateModel(
            name='StudentSTEPQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('is_solved', models.BooleanField(default=False, verbose_name='تم الحل (إجابة صحيحة أو show answer)')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('used_show_answer', models.BooleanField(default=False, verbose_name='استخدم show answer')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='step.stepskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student STEP Question Attempt',
                'verbose_name_plural': 'Student STEP Question Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='step_studen_student_f69645_idx'), models.Index(fields=['question_type', 'question_id'], name='step_studen_questio_d88468_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
    ]
