# Generated by Django 5.2 on 2026-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_studentstepprogress_viewed_questions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepskill',
            name='child_skills',
            field=models.ManyToManyField(blank=True, related_name='parent_paths', to='step.stepskill', verbose_name='المهارات الفرعية'),
        ),
        migrations.AlterField(
            model_name='stepskill',
            name='skill_type',
            field=models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('GENERAL_PATH', 'المسار العام')], max_length=20, verbose_name='نوع المهارة'),
        ),
    ]
