# Generated by Django 5.2 on 2026-04-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البنك')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف البنك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'بنك أسئلة Placement',
                'verbose_name_plural': 'بنوك أسئلة Placement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الاختبار')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='المدة بالدقائق')),
                ('total_questions', models.PositiveIntegerField(default=50, verbose_name='إجمالي الأسئلة')),
                ('vocabulary_count', models.PositiveIntegerField(default=10, verbose_name='عدد أسئلة المفردات')),
                ('grammar_count', models.PositiveIntegerField(default=10, verbose_name='عدد أسئلة القواعد')),
                ('reading_count', models.PositiveIntegerField(default=6, verbose_name='عدد أسئلة القراءة')),
                ('listening_count', models.PositiveIntegerField(default=10, verbose_name='عدد أسئلة الاستماع')),
                ('speaking_count', models.PositiveIntegerField(default=10, verbose_name='عدد أسئلة التحدث')),
                ('writing_count', models.PositiveIntegerField(default=4, verbose_name='عدد أسئلة الكتابة')),
                ('a1_min_score', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى لـ A1')),
                ('a1_max_score', models.PositiveIntegerField(default=20, verbose_name='الحد الأقصى لـ A1')),
                ('a2_min_score', models.PositiveIntegerField(default=21, verbose_name='الحد الأدنى لـ A2')),
                ('a2_max_score', models.PositiveIntegerField(default=30, verbose_name='الحد الأقصى لـ A2')),
                ('b1_min_score', models.PositiveIntegerField(default=31, verbose_name='الحد الأدنى لـ B1')),
                ('b1_max_score', models.PositiveIntegerField(default=40, verbose_name='الحد الأقصى لـ B1')),
                ('b2_min_score', models.PositiveIntegerField(default=41, verbose_name='الحد الأدنى لـ B2')),
                ('b2_max_score', models.PositiveIntegerField(default=50, verbose_name='الحد الأقصى لـ B2')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'اختبار تحديد المستوى',
                'verbose_name_plural': 'اختبارات تحديد المستوى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='الدرجة')),
                ('level_achieved', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate')], max_length=2, null=True, verbose_name='المستوى المحقق')),
                ('selected_questions_json', models.TextField(blank=True, help_text='يحفظ معرفات الأسئلة المختارة عشوائياً', null=True, verbose_name='الأسئلة المختارة (JSON)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'جاري'), ('COMPLETED', 'مكتمل'), ('ABANDONED', 'متروك')], default='IN_PROGRESS', max_length=20, verbose_name='الحالة')),
                ('placement_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='placement_test.placementtest', verbose_name='اختبار تحديد المستوى')),
                ('question_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_attempts', to='placement_test.placementquestionbank', verbose_name='بنك الأسئلة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'محاولة طالب',
                'verbose_name_plural': 'محاولات الطلاب',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTestQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف السؤال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_placement_questions', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['vocabularyquestion', 'grammarquestion', 'readingquestion', 'listeningquestion', 'speakingquestion', 'writingquestion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع السؤال')),
                ('placement_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='placement_test.placementtest', verbose_name='اختبار تحديد المستوى')),
            ],
            options={
                'verbose_name': 'سؤال في بنك الاختبار',
                'verbose_name_plural': 'أسئلة بنك الاختبار',
                'ordering': ['-created_at'],
                'unique_together': {('placement_test', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف السؤال')),
                ('selected_choice', models.CharField(blank=True, choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, null=True, verbose_name='الاختيار المحدد')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة النصية')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيحة')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='ملاحظات الـ AI')),
                ('ai_grading_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model المستخدم')),
                ('ai_grading_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='تكلفة التصحيح ($)')),
                ('strengths', models.JSONField(blank=True, default=list, null=True, verbose_name='نقاط القوة')),
                ('improvements', models.JSONField(blank=True, default=list, null=True, verbose_name='نقاط التحسين')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='تم الإجابة في')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='الوقت المستغرق (بالثواني)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع السؤال')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement_test.studentplacementtestattempt', verbose_name='المحاولة')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'content_type', 'object_id')},
            },
        ),
    ]
