# Generated by Django 5.2 on 2026-02-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('placement_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestquestionbank',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_placement_questions', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة'),
        ),
        migrations.AddField(
            model_name='placementtestquestionbank',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['vocabularyquestion', 'grammarquestion', 'readingquestion', 'listeningquestion', 'speakingquestion', 'writingquestion']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع السؤال'),
        ),
        migrations.AddField(
            model_name='placementtestquestionbank',
            name='placement_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='placement_test.placementtest', verbose_name='اختبار تحديد المستوى'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع السؤال'),
        ),
        migrations.AddField(
            model_name='studentplacementtestattempt',
            name='placement_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='placement_test.placementtest', verbose_name='اختبار تحديد المستوى'),
        ),
        migrations.AddField(
            model_name='studentplacementtestattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement_test.studentplacementtestattempt', verbose_name='المحاولة'),
        ),
        migrations.AlterUniqueTogether(
            name='placementtestquestionbank',
            unique_together={('placement_test', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='studentplacementtestanswer',
            unique_together={('attempt', 'content_type', 'object_id')},
        ),
    ]
