# Generated by Django 5.2 on 2026-02-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplacementtestattempt',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_attempts', to='placement_test.questionbank', verbose_name='بنك الأسئلة'),
        ),
    ]
