# Generated by Django 5.2 on 2026-02-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0003_studentplacementtestattempt_question_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الـ AI'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='ai_grading_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='تكلفة التصحيح ($)'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='ai_grading_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model المستخدم'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='improvements',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='نقاط التحسين'),
        ),
        migrations.AddField(
            model_name='studentplacementtestanswer',
            name='strengths',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='نقاط القوة'),
        ),
    ]
