# Generated by Django 5.2 on 2026-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_test', '0004_studentplacementtestanswer_ai_feedback_and_more'),
        ('sabr_questions', '0003_grammarquestion_lesson_grammarquestion_level_exam_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionBank',
            new_name='PlacementQuestionBank',
        ),
        migrations.AlterModelOptions(
            name='placementquestionbank',
            options={'ordering': ['-created_at'], 'verbose_name': 'بنك أسئلة Placement', 'verbose_name_plural': 'بنوك أسئلة Placement'},
        ),
    ]
