# Generated by Django 5.2 on 2025-12-09 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], max_length=10, verbose_name='نوع المستخدم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, related_name='sabr_users', related_query_name='sabr_user', to='auth.group', verbose_name='المجموعات')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='sabr_users', related_query_name='sabr_user', to='auth.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/', verbose_name='صورة الملف الشخصي')),
                ('overall_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='المستوى العام')),
                ('reading_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى القراءة')),
                ('writing_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى الكتابة')),
                ('listening_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى الاستماع')),
                ('speaking_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى التحدث')),
                ('grammar_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى القواعد')),
                ('vocabulary_level', models.CharField(choices=[('not_tested', 'لم يتم الاختبار بعد'), ('A1', 'A1 - مبتدئ'), ('A2', 'A2 - أساسي'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط متقدم')], default='not_tested', max_length=20, verbose_name='مستوى المفردات')),
                ('placement_test_taken', models.BooleanField(default=False, verbose_name='تم إجراء اختبار تحديد المستوى')),
                ('placement_test_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اختبار تحديد المستوى')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عني')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
