# Generated by Django 5.2 on 2026-02-15 13:52

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('skill_type', models.CharField(choices=[('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('LISTENING', 'Listening')], max_length=20, unique=True, verbose_name='نوع المهارة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'IELTS Skill',
                'verbose_name_plural': 'IELTS Skills',
                'ordering': ['order', 'skill_type'],
            },
        ),
        migrations.CreateModel(
            name='LessonPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المجموعة')),
                ('exam_time_limit', models.PositiveIntegerField(default=30, verbose_name='وقت الامتحان (دقيقة)')),
                ('exam_passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النجاح (%)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_packs', to='ielts.ieltsskill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'Lesson Pack',
                'verbose_name_plural': 'Lesson Packs',
                'ordering': ['skill', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IELTSPracticeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(default='Practice Exam', max_length=200, verbose_name='عنوان الامتحان')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات الامتحان')),
                ('lesson_pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_exam', to='ielts.lessonpack', verbose_name='Lesson Pack')),
            ],
            options={
                'verbose_name': 'IELTS Practice Exam',
                'verbose_name_plural': 'IELTS Practice Exams',
            },
        ),
        migrations.CreateModel(
            name='IELTSLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدرس')),
                ('lesson_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ielts.lessonpack', verbose_name='Lesson Pack')),
            ],
            options={
                'verbose_name': 'IELTS Lesson',
                'verbose_name_plural': 'IELTS Lessons',
                'ordering': ['lesson_pack', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('audio_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='التسجيل الصوتي')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='النص الكتابي')),
                ('vocabulary_explanation', models.TextField(blank=True, null=True, verbose_name='شرح المفردات')),
                ('listening_exercises', models.JSONField(blank=True, default=list, help_text='[{"question": "What is the main idea?", "answer": "..."}]', verbose_name='تمارين استماع')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='نصائح الاستماع')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_content', to='ielts.ieltslesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'Listening Lesson Content',
                'verbose_name_plural': 'Listening Lesson Contents',
            },
        ),
        migrations.CreateModel(
            name='ReadingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reading_text', models.TextField(verbose_name='النص القرائي')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الدرس')),
                ('vocabulary_words', models.JSONField(blank=True, default=list, help_text='[{"word": "amazing", "meaning": "مدهش"}]', verbose_name='المفردات')),
                ('examples', models.TextField(blank=True, null=True, verbose_name='أمثلة')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو التعليمي')),
                ('resources', models.JSONField(blank=True, default=list, help_text='[{"title": "PDF Guide", "url": "https://..."}]', verbose_name='ملفات إضافية')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_content', to='ielts.ieltslesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'Reading Lesson Content',
                'verbose_name_plural': 'Reading Lesson Contents',
            },
        ),
        migrations.CreateModel(
            name='SpeakingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='فيديو تعليمي')),
                ('dialogue_texts', models.JSONField(blank=True, default=list, help_text='[{"speaker": "John", "text": "Hello!"}, {"speaker": "Mary", "text": "Hi!"}]', verbose_name='نصوص حوارية')),
                ('useful_phrases', models.JSONField(blank=True, default=list, help_text='["Let me think...", "In my opinion..."]', verbose_name='عبارات مفيدة')),
                ('audio_examples', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='أمثلة صوتية')),
                ('pronunciation_tips', models.TextField(blank=True, null=True, verbose_name='نصائح النطق')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_content', to='ielts.ieltslesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'Speaking Lesson Content',
                'verbose_name_plural': 'Speaking Lesson Contents',
            },
        ),
        migrations.CreateModel(
            name='SpeakingRecordingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('task_text', models.TextField(verbose_name='نص المهمة')),
                ('task_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة المهمة')),
                ('duration_seconds', models.PositiveIntegerField(default=120, verbose_name='المدة المطلوبة (ثانية)')),
                ('assess_content', models.BooleanField(default=True, verbose_name='تقييم المحتوى')),
                ('assess_grammar', models.BooleanField(default=True, verbose_name='تقييم القواعد')),
                ('assess_fluency', models.BooleanField(default=True, verbose_name='تقييم الطلاقة')),
                ('assess_pronunciation', models.BooleanField(default=False, verbose_name='تقييم النطق')),
                ('max_content_score', models.PositiveIntegerField(default=10, verbose_name='أقصى درجة للمحتوى')),
                ('max_grammar_score', models.PositiveIntegerField(default=10, verbose_name='أقصى درجة للقواعد')),
                ('max_fluency_score', models.PositiveIntegerField(default=10, verbose_name='أقصى درجة للطلاقة')),
                ('max_pronunciation_score', models.PositiveIntegerField(default=10, verbose_name='أقصى درجة للنطق')),
                ('lesson_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_recording_tasks', to='ielts.lessonpack', verbose_name='Lesson Pack')),
            ],
            options={
                'verbose_name': 'Speaking Recording Task',
                'verbose_name_plural': 'Speaking Recording Tasks',
                'ordering': ['lesson_pack', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentSpeakingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('audio_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='تسجيل الطالب')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='النص المكتوب (Whisper)')),
                ('transcription_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='نموذج التحويل')),
                ('transcribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('content_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='درجة المحتوى')),
                ('grammar_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='درجة القواعد')),
                ('fluency_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='درجة الطلاقة')),
                ('pronunciation_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='درجة النطق')),
                ('total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='الدرجة الإجمالية')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='ملاحظات الـ AI')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='["Good vocabulary", "Clear pronunciation"]', verbose_name='نقاط القوة')),
                ('improvements', models.JSONField(blank=True, default=list, help_text='["Work on past tense", "Speak more slowly"]', verbose_name='نقاط التحسين')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقييم')),
                ('assessment_model', models.CharField(blank=True, help_text='e.g., gpt-4, claude-3', max_length=50, null=True, verbose_name='نموذج التقييم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_recordings', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recordings', to='ielts.speakingrecordingtask', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'Student Speaking Recording',
                'verbose_name_plural': 'Student Speaking Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sample_texts', models.TextField(verbose_name='نصوص نموذجية')),
                ('writing_instructions', models.TextField(verbose_name='تعليمات الكتابة')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='نصائح وإرشادات')),
                ('examples', models.TextField(blank=True, null=True, verbose_name='أمثلة عملية')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو التعليمي')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_content', to='ielts.ieltslesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'Writing Lesson Content',
                'verbose_name_plural': 'Writing Lesson Contents',
            },
        ),
        migrations.CreateModel(
            name='StudentLessonPackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('lesson_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='ielts.lessonpack', verbose_name='Lesson Pack')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_lesson_pack_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student Lesson Pack Progress',
                'verbose_name_plural': 'Student Lesson Pack Progress',
                'ordering': ['student', 'lesson_pack'],
                'unique_together': {('student', 'lesson_pack')},
            },
        ),
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='ielts.ieltslesson', verbose_name='الدرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student Lesson Progress',
                'verbose_name_plural': 'Student Lesson Progress',
                'ordering': ['student', 'lesson'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentPracticeExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='رقم المحاولة')),
                ('answers', models.JSONField(default=dict, help_text='\n        {\n            "vocabulary_1": "A",\n            "reading_passage_1_q1": "B",\n            "writing_1": "text of answer...",\n            "speaking_recording_1": "recording_id"\n        }\n        ', verbose_name='الإجابات')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='نجح')),
                ('time_taken', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوقت المستغرق (ثانية)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('practice_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ielts.ieltspracticeexam', verbose_name='Practice Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student Practice Exam Attempt',
                'verbose_name_plural': 'Student Practice Exam Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'practice_exam', 'attempt_number')},
            },
        ),
    ]
