# Generated by Django 5.2 on 2026-04-09 11:08

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الكتاب')),
                ('pdf_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف PDF')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='النص المستخرج')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_extracted_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracted Book',
                'verbose_name_plural': 'Extracted Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الميديا')),
                ('media_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف الميديا')),
                ('media_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=10)),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='الترانسكريبت')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_extracted_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracted Media',
                'verbose_name_plural': 'Extracted Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('skill_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('GENERAL_PATH', 'General path'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع المهارة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الأيقونة')),
                ('child_skills', models.ManyToManyField(blank=True, related_name='parent_paths', to='ielts.ieltsskill', verbose_name='المهارات الفرعية')),
            ],
            options={
                'verbose_name': 'IELTS Skill',
                'verbose_name_plural': 'IELTS Skills',
                'ordering': ['order', 'skill_type'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=20)),
                ('skill_title', models.CharField(max_length=200)),
                ('skill_description', models.TextField(blank=True, null=True)),
                ('no_easy', models.PositiveIntegerField(default=0)),
                ('no_medium', models.PositiveIntegerField(default=0)),
                ('no_hard', models.PositiveIntegerField(default=0)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('questions_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(blank=True, related_name='ielts_generation_jobs', to='ielts.extractedbook')),
                ('media', models.ManyToManyField(blank=True, related_name='ielts_generation_jobs', to='ielts.extractedmedia')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_generation_jobs', to='ielts.ieltsskill')),
            ],
            options={
                'verbose_name': 'AI Generation Job',
                'verbose_name_plural': 'AI Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentIELTSProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('viewed_questions_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة المكتملة')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='ielts.ieltsskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student IELTS Progress',
                'verbose_name_plural': 'Student IELTS Progress',
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentIELTSQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('is_solved', models.BooleanField(default=False, verbose_name='تم الحل (إجابة صحيحة أو show answer)')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('used_show_answer', models.BooleanField(default=False, verbose_name='استخدم show answer')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='ielts.ieltsskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student IELTS Question Attempt',
                'verbose_name_plural': 'Student IELTS Question Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='ielts_stude_student_4dc154_idx'), models.Index(fields=['question_type', 'question_id'], name='ielts_stude_questio_47df23_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentIELTSQuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=20, verbose_name='نوع السؤال')),
                ('question_id', models.PositiveIntegerField(verbose_name='رقم السؤال')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفتح')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='ielts.ieltsskill', verbose_name='المهارة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_question_views', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'Student IELTS Question View',
                'verbose_name_plural': 'Student IELTS Question Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', 'skill'], name='ielts_stude_student_9a1173_idx'), models.Index(fields=['question_type', 'question_id'], name='ielts_stude_questio_6e38df_idx')],
                'unique_together': {('student', 'question_type', 'question_id')},
            },
        ),
    ]
