# Generated by Django 5.2 on 2026-04-09 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ielts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractedbook',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_extracted_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aigenerationjob',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='ielts_generation_jobs', to='ielts.extractedbook'),
        ),
        migrations.AddField(
            model_name='extractedmedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_extracted_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aigenerationjob',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='ielts_generation_jobs', to='ielts.extractedmedia'),
        ),
        migrations.AddField(
            model_name='ieltsskill',
            name='child_skills',
            field=models.ManyToManyField(blank=True, related_name='parent_paths', to='ielts.ieltsskill', verbose_name='المهارات الفرعية'),
        ),
        migrations.AddField(
            model_name='aigenerationjob',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_generation_jobs', to='ielts.ieltsskill'),
        ),
        migrations.AddField(
            model_name='studentieltsprogress',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='ielts.ieltsskill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='studentieltsprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentieltsquestionattempt',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='ielts.ieltsskill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='studentieltsquestionattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentieltsquestionview',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='ielts.ieltsskill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='studentieltsquestionview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_question_views', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AlterUniqueTogether(
            name='studentieltsprogress',
            unique_together={('student', 'skill')},
        ),
        migrations.AddIndex(
            model_name='studentieltsquestionattempt',
            index=models.Index(fields=['student', 'skill'], name='ielts_stude_student_4dc154_idx'),
        ),
        migrations.AddIndex(
            model_name='studentieltsquestionattempt',
            index=models.Index(fields=['question_type', 'question_id'], name='ielts_stude_questio_47df23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentieltsquestionattempt',
            unique_together={('student', 'question_type', 'question_id')},
        ),
        migrations.AddIndex(
            model_name='studentieltsquestionview',
            index=models.Index(fields=['student', 'skill'], name='ielts_stude_student_9a1173_idx'),
        ),
        migrations.AddIndex(
            model_name='studentieltsquestionview',
            index=models.Index(fields=['question_type', 'question_id'], name='ielts_stude_questio_6e38df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentieltsquestionview',
            unique_together={('student', 'question_type', 'question_id')},
        ),
    ]
