# Generated by Django 5.2 on 2026-02-08 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabr_questions', '0002_writingquestion_pass_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('lesson_type', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing')], max_length=20, verbose_name='نوع الدرس')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['unit', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('code', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate')], max_length=2, unique=True, verbose_name='كود المستوى')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستوى')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المستوى')),
            ],
            options={
                'verbose_name': 'مستوى تعليمي',
                'verbose_name_plural': 'المستويات التعليمية',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LevelExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(default='Level Exam', max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الامتحان')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات الامتحان')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='الوقت المخصص (دقيقة)')),
                ('passing_score', models.PositiveIntegerField(default=70, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النجاح (%)')),
                ('vocabulary_count', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة المفردات')),
                ('grammar_count', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة القواعد')),
                ('reading_questions_count', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة القراءة')),
                ('listening_questions_count', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة الاستماع')),
                ('speaking_questions_count', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة التحدث')),
                ('writing_questions_count', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة الكتابة')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='levels.level', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'امتحان مستوى',
                'verbose_name_plural': 'امتحانات المستويات',
                'ordering': ['level__order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الدرس')),
                ('audio', models.ForeignKey(help_text='يحتوي على: العنوان، الملف الصوتي، النص، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.listeningaudio', verbose_name='التسجيل الصوتي')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'LISTENING'}, on_delete=django.db.models.deletion.CASCADE, related_name='listening_content', to='levels.lesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'محتوى درس استماع',
                'verbose_name_plural': 'محتويات دروس الاستماع',
            },
        ),
        migrations.CreateModel(
            name='ReadingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('vocabulary_words', models.JSONField(blank=True, default=list, help_text='مثال: [{"english_word": "dog", "translate": "كلب"}]', verbose_name='المفردات')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الدرس')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'READING'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading_content', to='levels.lesson', verbose_name='الدرس')),
                ('passage', models.ForeignKey(help_text='القطعة تحتوي على: العنوان، النص، الصورة، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.readingpassage', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'محتوى درس قراءة',
                'verbose_name_plural': 'محتويات دروس القراءة',
            },
        ),
        migrations.CreateModel(
            name='SpeakingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الدرس')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'SPEAKING'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_content', to='levels.lesson', verbose_name='الدرس')),
                ('video', models.ForeignKey(help_text='يحتوي على: العنوان، الفيديو، النص، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.speakingvideo', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'محتوى درس تحدث',
                'verbose_name_plural': 'محتويات دروس التحدث',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوحدة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الوحدة')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='levels.level', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'وحدة دراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'ordering': ['level', 'order', 'id'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='levels.unit', verbose_name='الوحدة'),
        ),
        migrations.CreateModel(
            name='UnitExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('title', models.CharField(default='Unit Exam', max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الامتحان')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات الامتحان')),
                ('time_limit', models.PositiveIntegerField(default=35, help_text='سؤال واحد = دقيقة واحدة', verbose_name='الوقت المخصص (دقيقة)')),
                ('passing_score', models.PositiveIntegerField(default=70, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة النجاح (%)')),
                ('vocabulary_count', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة المفردات')),
                ('grammar_count', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة القواعد')),
                ('reading_questions_count', models.PositiveIntegerField(default=10, help_text='سيتم اختيار قطع قراءة تحتوي على هذا العدد من الأسئلة تقريباً', validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة القراءة')),
                ('listening_questions_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة الاستماع')),
                ('speaking_questions_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة التحدث')),
                ('writing_questions_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد أسئلة الكتابة')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='levels.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'امتحان وحدة',
                'verbose_name_plural': 'امتحانات الوحدات',
                'ordering': ['unit__level', 'unit__order'],
            },
        ),
        migrations.CreateModel(
            name='WritingLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان المحتوى')),
                ('writing_passage', models.TextField(help_text='مثال أو نموذج للطالب', verbose_name='قطعة كتابية نموذجية')),
                ('instructions', models.TextField(help_text='إرشادات وتوجيهات للطالب', verbose_name='تعليمات الكتابة')),
                ('sample_answer', models.TextField(blank=True, null=True, verbose_name='نموذج إجابة')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'WRITING'}, on_delete=django.db.models.deletion.CASCADE, related_name='writing_content', to='levels.lesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'محتوى درس كتابة',
                'verbose_name_plural': 'محتويات دروس الكتابة',
            },
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.lesson', verbose_name='الدرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقدم الطالب في الدرس',
                'verbose_name_plural': 'تقدم الطلاب في الدروس',
                'ordering': ['student', 'lesson__unit', 'lesson__order'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentLevelExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='رقم المحاولة')),
                ('generated_questions', models.JSONField(default=dict, verbose_name='الأسئلة المولّدة')),
                ('answers', models.JSONField(default=dict, verbose_name='الإجابات')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة (من 100)')),
                ('passed', models.BooleanField(default=False, verbose_name='نجح')),
                ('time_taken', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوقت المستغرق (ثانية)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('level_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='levels.levelexam', verbose_name='امتحان المستوى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'محاولة امتحان مستوى',
                'verbose_name_plural': 'محاولات امتحانات المستويات',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'level_exam', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=20, verbose_name='الحالة')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='الدروس المكتملة')),
                ('exam_passed', models.BooleanField(default=False, verbose_name='نجح في الامتحان')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_units', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'تقدم الطالب في الوحدة',
                'verbose_name_plural': 'تقدم الطلاب في الوحدات',
                'ordering': ['student', 'unit__level', 'unit__order'],
                'unique_together': {('student', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.level', verbose_name='المستوى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('current_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.unit', verbose_name='الوحدة الحالية')),
            ],
            options={
                'verbose_name': 'تقدم الطالب في المستوى',
                'verbose_name_plural': 'تقدم الطلاب في المستويات',
                'ordering': ['student', 'level__order'],
                'unique_together': {('student', 'level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
        migrations.CreateModel(
            name='StudentUnitExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='رقم المحاولة')),
                ('generated_questions', models.JSONField(default=dict, help_text='\n        {\n            "vocabulary_questions": [1, 5, 8, ...],\n            "grammar_questions": [2, 4, 9, ...],\n            "reading_passages": [3, 7],\n            "listening_audios": [6],\n            "speaking_videos": [10],\n            "writing_questions": [11]\n        }\n        ', verbose_name='الأسئلة المولّدة')),
                ('answers', models.JSONField(default=dict, help_text='\n        {\n            "vocabulary_1": "A",\n            "grammar_2": "B",\n            "reading_3_1": "C",\n            "writing_11": "text of student answer..."\n        }\n        ', verbose_name='الإجابات')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة (من 100)')),
                ('passed', models.BooleanField(default=False, verbose_name='نجح')),
                ('time_taken', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوقت المستغرق (ثانية)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('unit_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='levels.unitexam', verbose_name='امتحان الوحدة')),
            ],
            options={
                'verbose_name': 'محاولة امتحان وحدة',
                'verbose_name_plural': 'محاولات امتحانات الوحدات',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'unit_exam', 'attempt_number')},
            },
        ),
    ]
