# Generated by Django 5.2 on 2026-01-13 10:51

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التمرين')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف التمرين')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'التمارين',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'مستوى',
                'verbose_name_plural': 'المستويات',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening_speaking', 'Listening & Speaking'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('vocabulary', 'Vocabulary'), ('writing', 'Writing'), ('interactive', 'Interactive Exercises'), ('quiz', 'Quiz')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان التسجيل')),
                ('audio_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='النص الكتابي للتسجيل')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='المدة بالثواني', null=True, verbose_name='مدة التسجيل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_audios', to='levels.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'تسجيل صوتي للتمرين',
                'verbose_name_plural': 'التسجيلات الصوتية للتمارين',
                'ordering': ['exercise', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levels.exerciselisteningaudio', verbose_name='التسجيل الصوتي')),
            ],
            options={
                'verbose_name': 'سؤال استماع للتمرين',
                'verbose_name_plural': 'أسئلة الاستماع للتمارين',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='levels.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'سؤال MCQ للتمرين',
                'verbose_name_plural': 'أسئلة MCQ للتمارين',
                'ordering': ['exercise', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان القطعة')),
                ('passage_text', models.TextField(verbose_name='نص القطعة')),
                ('passage_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='مصدر القطعة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='levels.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'قطعة قراءة للتمرين',
                'verbose_name_plural': 'قطع القراءة للتمارين',
                'ordering': ['exercise', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levels.exercisereadingpassage', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'سؤال قراءة للتمرين',
                'verbose_name_plural': 'أسئلة القراءة للتمارين',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSpeakingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان الفيديو')),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفيديو')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='المدة بالثواني', null=True, verbose_name='مدة الفيديو')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_videos', to='levels.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'فيديو تحدث للتمرين',
                'verbose_name_plural': 'فيديوهات التحدث للتمارين',
                'ordering': ['exercise', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار أ')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار ب')),
                ('choice_c', models.CharField(max_length=500, verbose_name='الاختيار ج')),
                ('choice_d', models.CharField(max_length=500, verbose_name='الاختيار د')),
                ('correct_answer', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levels.exercisespeakingvideo', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'سؤال تحدث للتمرين',
                'verbose_name_plural': 'أسئلة التحدث للتمارين',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseWritingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('min_words', models.PositiveIntegerField(default=100, verbose_name='الحد الأدنى للكلمات')),
                ('max_words', models.PositiveIntegerField(default=500, verbose_name='الحد الأقصى للكلمات')),
                ('sample_answer', models.TextField(blank=True, null=True, verbose_name='نموذج إجابة')),
                ('rubric', models.TextField(blank=True, help_text='معايير تقييم الإجابة', null=True, verbose_name='معايير التقييم')),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='النقاط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_questions', to='levels.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'سؤال كتابة للتمرين',
                'verbose_name_plural': 'أسئلة الكتابة للتمارين',
                'ordering': ['exercise', 'order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='levels.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='levels.section'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='levels.level')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['level', 'number'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='levels.unit'),
        ),
    ]
