# Generated by Django 5.2 on 2026-04-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
        ('sabr_questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninglessoncontent',
            name='audio',
            field=models.ForeignKey(help_text='يحتوي على: العنوان، الملف الصوتي، النص، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.listeningaudio', verbose_name='التسجيل الصوتي'),
        ),
        migrations.AddField(
            model_name='listeninglessoncontent',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'lesson_type': 'LISTENING'}, on_delete=django.db.models.deletion.CASCADE, related_name='listening_content', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='readinglessoncontent',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'lesson_type': 'READING'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading_content', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='readinglessoncontent',
            name='passage',
            field=models.ForeignKey(help_text='القطعة تحتوي على: العنوان، النص، الصورة، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.readingpassage', verbose_name='القطعة'),
        ),
        migrations.AddField(
            model_name='speakinglessoncontent',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'lesson_type': 'SPEAKING'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_content', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='speakinglessoncontent',
            name='video',
            field=models.ForeignKey(help_text='يحتوي على: العنوان، الفيديو، النص، الأسئلة المحلولة', on_delete=django.db.models.deletion.CASCADE, to='sabr_questions.speakingvideo', verbose_name='الفيديو'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.level', verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentlevelexamattempt',
            name='level_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='levels.levelexam', verbose_name='امتحان المستوى'),
        ),
        migrations.AddField(
            model_name='studentlevelexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentunit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_units', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='studentunitexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='levels.level', verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='studentunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='levels.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='current_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.unit', verbose_name='الوحدة الحالية'),
        ),
        migrations.AddField(
            model_name='levelsunitsquestionbank',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='levels.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='levels.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='unitexam',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='levels.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='studentunitexamattempt',
            name='unit_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='levels.unitexam', verbose_name='امتحان الوحدة'),
        ),
        migrations.AddField(
            model_name='writinglessoncontent',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'lesson_type': 'WRITING'}, on_delete=django.db.models.deletion.CASCADE, related_name='writing_content', to='levels.lesson', verbose_name='الدرس'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlesson',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='studentlevelexamattempt',
            unique_together={('student', 'level_exam', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('level', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='studentunit',
            unique_together={('student', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='studentlevel',
            unique_together={('student', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='studentunitexamattempt',
            unique_together={('student', 'unit_exam', 'attempt_number')},
        ),
    ]
