# Generated by Django 5.2 on 2026-02-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البنك')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف البنك')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='levels.level', verbose_name='المستوى')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='levels.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'بنك أسئلة',
                'verbose_name_plural': 'بنوك الأسئلة',
                'ordering': ['-created_at'],
            },
        ),
    ]
